codecov:
  notify:
    require_ci_to_pass: no

comment:
  layout: "reach, diff"
  behavior: default

fixes:
  - "AppVeyor/::"

coverage:
  range: 50..80
  round: down
  precision: 0

  status:
    project:
      default:
        target: 70
    patch:
      default:
        # Set the pull request requirement to not regress overall coverage by more than 5%
        # and let codecov.io set the goal for the code changed in the patch.
        target: auto
        threshold: 5
